(define (problem pb1)
  (:domain kitchenDomain)
  (:init 
    (arm-empty)
    (spam-on-countertop)
    (sugar-on-stovetop)
    (drawer-closed)
  )
  (:goal (and
    (sugar-on-countertop)
    (spam-in-drawer)
    (drawer-closed)
    (arm-empty)
  ))
)